name: "units-test"
on:
  # works for mannual, in case of github agent updated. 
  # we can run mannually to see if it can be fixed by update version of
  # - kubectl
  # - k8s cluster provider's 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x

  # test local cluster start up
  test_local_cluster:
    needs:
      - shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # I suppose we'd better update version pre kepler release.
        # keep from current default version and latest version.
        cluster_provider: [kind, microshift]
        kubectl_version: [v1.27.2]
        # So far we just have a single version for microshift
        # in the future, we should considering have a local test for each cluster providers
        kind_version: [0.19.0]
    steps:
    - uses: actions/checkout@v3
    - name: kubectl
      run: curl -LO https://dl.k8s.io/release/${{matrix.kubectl_version}}/bin/linux/amd64/kubectl
    - name: start from local
      run: | 
        export KIND_VERSION=${{matrix.kind_version}}
        export CLUSTER_PROVIDER=${{matrix.cluster_provider}}
        ./main.sh up
    - name: verify
      run: |
        export CLUSTER_PROVIDER=${{matrix.cluster_provider}}
        ./verify.sh

# test local cluster with prometheus grafana
  test_local_cluster_with_prometheus_grafana:
    runs-on: ubuntu-latest
    needs: test_local_cluster
    strategy:
      matrix:
        # I suppose we'd better update version pre kepler release.
        # keep from current default version and latest version.
        cluster_provider: [kind, microshift]
        prometheus_operator_version: [v0.12.0]
    steps:
    - uses: actions/checkout@v3
    - name: kubectl
      run: curl -LO https://dl.k8s.io/release/v1.25.4/bin/linux/amd64/kubectl
    - name: start from local
      run: | 
        export PROMETHEUS_ENABLE=true
        export PROMETHEUS_OPERATOR_VERSION=${{matrix.prometheus_operator_version}}
        export GRAFANA_ENABLE=true
        export CLUSTER_PROVIDER=${{matrix.cluster_provider}}
        ./main.sh up
    - name: verify
      run: |
        export CLUSTER_PROVIDER=${{matrix.cluster_provider}}
        ./verify.sh
